### ISSUE TITLE
Converting Mutiverse Invetory data back to normal minecraft data

### ISSUE THREAD

**Issue by Ryamonster10** [phildier/dat_converter#4]
Hi! Your script works great! However, is there a way to go the other way around?

**Comment by phildier** [comment]
sorry, it's just the one way

**Comment by Ryamonster10** [comment]
Ok, two more quick questions:
1: Does it convert player location?
2: Does it work for the lastest version of minecraft?

**Comment by phildier** [comment]
1: no, just inventory
2: maybe?  not sure if the dat file format has changed or not
